//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ksenia
{
    using System;
    using System.Collections.Generic;
    
    public partial class Booking
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Booking()
        {
            this.Payment = new HashSet<Payment>();
        }
    
        public int ID_Reservations { get; set; }
        public Nullable<int> ID_Guest { get; set; }
        public Nullable<int> ID_Room { get; set; }
        public Nullable<System.DateTime> Check_in_date { get; set; }
        public Nullable<System.DateTime> Departure_date { get; set; }
        public Nullable<int> Number_of_guests { get; set; }
        public Nullable<decimal> Booking_amount { get; set; }
        public string Booking_status { get; set; }
    
        public virtual Guest Guest { get; set; }
        public virtual Room Room { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Payment> Payment { get; set; }
    }
}
