//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ksenia
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payment
    {
        public int ID_Payment { get; set; }
        public int ID_Reservations { get; set; }
        public DateTime Payment_date { get; set; }
        public decimal Payment_amount { get; set; }
        public string PaymentMethod { get; set; }
    }
}
