//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ksenia
{
    using System;
    using System.Collections.Generic;
    
    public partial class Service
    {
        public int ID_Service { get; set; }
        public int ID_Employee { get; set; }
        public string Name_Service { get; set; }
        public string Description_Service { get; set; }
        public decimal Cost_of_service { get; set; }
    }
}
